/**
 * Template for generating table-specific React hooks
 * 
 * This template is used by the schema generation script to create
 * type-safe hooks for each Airtable table.
 */

export interface HookTemplateData {
  tableName: string;
  interfaceName: string;
  recordTypeName: string;
  hookName: string;
  timestamp: string;
}

export const generateHookTemplate = (data: HookTemplateData): string => {
  const { tableName, interfaceName, recordTypeName, hookName, timestamp } = data;
  
  return `/**
 * ${hookName} Hook
 * Auto-generated on ${timestamp}
 * 
 * This hook provides type-safe access to the '${tableName}' table.
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated when you run 'npm run generate:schema'
 */

import { useAirtableRecords } from '../useAirtableRecords';
import type { ${interfaceName}, ${recordTypeName} } from '../../services/airtable/generated/tables.types';

/**
 * Hook for fetching records from the ${tableName} table
 * 
 * @param filterFormula - Optional Airtable filter formula
 * @returns Object containing data, loading state, error, and refetch function
 * 
 * @example
 * \`\`\`typescript
 * const { data, loading, error, refetch } = ${hookName}("{Status} = 'Active'");
 * 
 * if (loading) return <div>Loading...</div>;
 * if (error) return <div>Error: {error.message}</div>;
 * 
 * return (
 *   <div>
 *     {data?.map(record => (
 *       <div key={record.id}>{JSON.stringify(record.fields)}</div>
 *     ))}
 *   </div>
 * );
 * \`\`\`
 */
export const ${hookName} = (filterFormula?: string) => {
  return useAirtableRecords<${interfaceName}>('${tableName}', filterFormula);
};
`;
};
