/**
 * Template for generating table-specific service files
 * 
 * This template is used by the schema generation script to create
 * type-safe service layers for each Airtable table.
 */

export interface ServiceTemplateData {
  tableName: string;
  interfaceName: string;
  recordTypeName: string;
  timestamp: string;
}

export const generateServiceTemplate = (data: ServiceTemplateData): string => {
  const { tableName, interfaceName, recordTypeName, timestamp } = data;
  
  return `/**
 * ${interfaceName} Service
 * Auto-generated on ${timestamp}
 * 
 * This file provides type-safe methods for interacting with the '${tableName}' table.
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated when you run 'npm run generate:schema'
 */

import { getTable } from '../client';
import { AirtableError } from '../types';
import { ${interfaceName}, ${recordTypeName} } from './tables.types';

/**
 * Service for the ${tableName} table
 */
export const ${interfaceName}Service = {
  /**
   * Get all records from the ${tableName} table
   * 
   * @returns Promise resolving to array of ${recordTypeName}
   * @throws AirtableError if the request fails
   */
  async getAll(): Promise<${recordTypeName}[]> {
    try {
      const table = getTable<${interfaceName}>('${tableName}');
      const records: ${recordTypeName}[] = [];

      await table.select().eachPage((pageRecords, fetchNextPage) => {
        pageRecords.forEach((record) => {
          records.push({
            id: record.id,
            fields: record.fields as ${interfaceName},
            createdTime: record.get('_createdTime') as string || new Date().toISOString(),
          });
        });
        fetchNextPage();
      });

      return records;
    } catch (error) {
      throw new AirtableError(
        \`Failed to fetch all ${tableName} records\`,
        undefined,
        error instanceof Error ? error : undefined
      );
    }
  },

  /**
   * Get a single record by ID from the ${tableName} table
   * 
   * @param id - Airtable record ID
   * @returns Promise resolving to ${recordTypeName}
   * @throws AirtableError if the request fails or record not found
   */
  async getById(id: string): Promise<${recordTypeName}> {
    try {
      const table = getTable<${interfaceName}>('${tableName}');
      const record = await table.find(id);

      return {
        id: record.id,
        fields: record.fields as ${interfaceName},
        createdTime: record.get('_createdTime') as string || new Date().toISOString(),
      };
    } catch (error) {
      throw new AirtableError(
        \`Failed to fetch ${tableName} record with id: \${id}\`,
        undefined,
        error instanceof Error ? error : undefined
      );
    }
  },

  /**
   * Get records matching a filter formula from the ${tableName} table
   * 
   * @param filterFormula - Airtable filter formula
   * @returns Promise resolving to array of ${recordTypeName}
   * @throws AirtableError if the request fails
   * 
   * @example
   * getByFilter("{Status} = 'Active'")
   */
  async getByFilter(filterFormula: string): Promise<${recordTypeName}[]> {
    try {
      const table = getTable<${interfaceName}>('${tableName}');
      const records: ${recordTypeName}[] = [];

      await table
        .select({ filterByFormula: filterFormula })
        .eachPage((pageRecords, fetchNextPage) => {
          pageRecords.forEach((record) => {
            records.push({
              id: record.id,
              fields: record.fields as ${interfaceName},
              createdTime: record.get('_createdTime') as string || new Date().toISOString(),
            });
          });
          fetchNextPage();
        });

      return records;
    } catch (error) {
      throw new AirtableError(
        \`Failed to fetch ${tableName} records with filter: \${filterFormula}\`,
        undefined,
        error instanceof Error ? error : undefined
      );
    }
  },

  // Future methods - uncomment and implement as needed:
  
  // /**
  //  * Create a new record in the ${tableName} table
  //  * 
  //  * @param fields - Field values for the new record
  //  * @returns Promise resolving to the created ${recordTypeName}
  //  */
  // async create(fields: ${interfaceName}): Promise<${recordTypeName}> {
  //   const table = getTable<${interfaceName}>('${tableName}');
  //   const record = await table.create(fields as any);
  //   return {
  //     id: record.id,
  //     fields: record.fields as ${interfaceName},
  //     createdTime: record.get('_createdTime') as string || new Date().toISOString(),
  //   };
  // },

  // /**
  //  * Update an existing record in the ${tableName} table
  //  * 
  //  * @param id - Airtable record ID
  //  * @param fields - Partial field values to update
  //  * @returns Promise resolving to the updated ${recordTypeName}
  //  */
  // async update(id: string, fields: Partial<${interfaceName}>): Promise<${recordTypeName}> {
  //   const table = getTable<${interfaceName}>('${tableName}');
  //   const record = await table.update(id, fields as any);
  //   return {
  //     id: record.id,
  //     fields: record.fields as ${interfaceName},
  //     createdTime: record.get('_createdTime') as string || new Date().toISOString(),
  //   };
  // },

  // /**
  //  * Delete a record from the ${tableName} table
  //  * 
  //  * @param id - Airtable record ID
  //  */
  // async delete(id: string): Promise<void> {
  //   const table = getTable<${interfaceName}>('${tableName}');
  //   await table.destroy(id);
  // },

  // /**
  //  * Bulk create records in the ${tableName} table
  //  * 
  //  * @param records - Array of field objects to create
  //  * @returns Promise resolving to array of created ${recordTypeName}
  //  */
  // async bulkCreate(records: ${interfaceName}[]): Promise<${recordTypeName}[]> {
  //   const table = getTable<${interfaceName}>('${tableName}');
  //   const createdRecords = await table.create(records as any[]);
  //   return createdRecords.map(record => ({
  //     id: record.id,
  //     fields: record.fields as ${interfaceName},
  //     createdTime: record.get('_createdTime') as string || new Date().toISOString(),
  //   }));
  // },
};
`;
};
