/**
 * Airtable Schema Generator
 * 
 * This script fetches the schema from Airtable Metadata API and generates:
 * 1. TypeScript interfaces for each table's fields
 * 2. Table-specific service files with typed methods
 * 3. Table-specific React hooks
 * 
 * Usage: npm run generate:schema
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { generateServiceTemplate } from './templates/service.template';
import { generateHookTemplate } from './templates/hook.template';

// Load environment variables
dotenv.config();

const PAT = process.env.VITE_AIRTABLE_PAT;
const BASE_ID = process.env.VITE_AIRTABLE_BASE_ID;

if (!PAT || !BASE_ID) {
  console.error('❌ Error: Missing Airtable credentials');
  console.error('Please ensure VITE_AIRTABLE_PAT and VITE_AIRTABLE_BASE_ID are set in your .env file');
  process.exit(1);
}

// Paths
const GENERATED_TYPES_PATH = path.join(process.cwd(), 'src/services/airtable/generated/tables.types.ts');
const GENERATED_SERVICES_DIR = path.join(process.cwd(), 'src/services/airtable/generated');
const GENERATED_HOOKS_DIR = path.join(process.cwd(), 'src/hooks/generated');

/**
 * Airtable API types
 */
interface AirtableField {
  id: string;
  name: string;
  type: string;
  options?: {
    choices?: Array<{ id: string; name: string; color?: string }>;
    [key: string]: any;
  };
}

interface AirtableTable {
  id: string;
  name: string;
  primaryFieldId: string;
  fields: AirtableField[];
}

interface AirtableSchema {
  tables: AirtableTable[];
}

/**
 * Map Airtable field types to TypeScript types
 */
const mapFieldType = (field: AirtableField): string => {
  switch (field.type) {
    case 'singleLineText':
    case 'multilineText':
    case 'richText':
    case 'email':
    case 'url':
    case 'phoneNumber':
      return 'string';
    
    case 'number':
    case 'currency':
    case 'percent':
    case 'duration':
    case 'rating':
      return 'number';
    
    case 'checkbox':
      return 'boolean';
    
    case 'singleSelect':
      if (field.options?.choices && field.options.choices.length > 0) {
        const choices = field.options.choices.map(c => `'${c.name}'`).join(' | ');
        return choices;
      }
      return 'string';
    
    case 'multipleSelects':
      return 'string[]';
    
    case 'date':
    case 'dateTime':
    case 'createdTime':
    case 'lastModifiedTime':
      return 'string';
    
    case 'multipleAttachments':
      return 'Attachment[]';
    
    case 'singleCollaborator':
      return '{ id: string; email: string; name?: string }';
    
    case 'multipleCollaborators':
      return 'Array<{ id: string; email: string; name?: string }>';
    
    case 'multipleRecordLinks':
      return 'string[]';
    
    case 'formula':
    case 'rollup':
    case 'lookup':
      // These depend on the underlying field type, default to any
      return 'any';
    
    case 'barcode':
      return '{ text: string; type?: string }';
    
    case 'button':
      return '{ label: string; url: string }';
    
    case 'count':
      return 'number';
    
    case 'autoNumber':
      return 'number';
    
    default:
      console.warn(`⚠️  Unknown field type: ${field.type} for field: ${field.name}`);
      return 'any';
  }
};

/**
 * Convert table name to PascalCase interface name
 */
const toPascalCase = (str: string): string => {
  return str
    .split(/[\s_-]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
};

/**
 * Convert table name to camelCase hook name
 */
const toCamelCase = (str: string): string => {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

/**
 * Fetch schema from Airtable Metadata API
 */
const fetchSchema = async (): Promise<AirtableSchema> => {
  const url = `https://api.airtable.com/v0/meta/bases/${BASE_ID}/tables`;
  
  console.log('🔍 Fetching schema from Airtable...');
  
  const response = await fetch(url, {
    headers: {
      'Authorization': `Bearer ${PAT}`,
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to fetch schema: ${response.status} ${response.statusText}\n${errorText}`);
  }

  const data = await response.json();
  return data as AirtableSchema;
};

/**
 * Generate TypeScript interfaces for all tables
 */
const generateTypesFile = (schema: AirtableSchema): string => {
  const timestamp = new Date().toLocaleString();
  
  let content = `/**
 * Airtable Table Types
 * Auto-generated on ${timestamp}
 * 
 * This file contains TypeScript interfaces for all tables in your Airtable base.
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated when you run 'npm run generate:schema'
 */

import { Attachment } from '../types';

`;

  schema.tables.forEach(table => {
    const interfaceName = `${toPascalCase(table.name)}Fields`;
    const recordTypeName = `${toPascalCase(table.name)}Record`;

    // Generate Fields interface
    content += `/**\n * Fields for the '${table.name}' table\n */\n`;
    content += `export interface ${interfaceName} {\n`;
    
    table.fields.forEach(field => {
      const fieldType = mapFieldType(field);
      // Make all fields optional since Airtable allows empty fields
      content += `  '${field.name}'?: ${fieldType};\n`;
    });
    
    content += `}\n\n`;

    // Generate Record type
    content += `/**\n * Record type for the '${table.name}' table\n */\n`;
    content += `export interface ${recordTypeName} {\n`;
    content += `  id: string;\n`;
    content += `  fields: ${interfaceName};\n`;
    content += `  createdTime: string;\n`;
    content += `}\n\n`;
  });

  return content;
};

/**
 * Generate service file for a table
 */
const generateServiceFile = (table: AirtableTable): string => {
  const timestamp = new Date().toLocaleString();
  const interfaceName = `${toPascalCase(table.name)}Fields`;
  const recordTypeName = `${toPascalCase(table.name)}Record`;

  return generateServiceTemplate({
    tableName: table.name,
    interfaceName,
    recordTypeName,
    timestamp,
  });
};

/**
 * Generate hook file for a table
 */
const generateHookFile = (table: AirtableTable): string => {
  const timestamp = new Date().toLocaleString();
  const interfaceName = `${toPascalCase(table.name)}Fields`;
  const recordTypeName = `${toPascalCase(table.name)}Record`;
  const hookName = `use${toPascalCase(table.name)}`;

  return generateHookTemplate({
    tableName: table.name,
    interfaceName,
    recordTypeName,
    hookName,
    timestamp,
  });
};

/**
 * Write file to disk
 */
const writeFile = (filePath: string, content: string): void => {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, content, 'utf-8');
};

/**
 * Main generation function
 */
const main = async () => {
  try {
    console.log('🚀 Starting schema generation...\n');

    // Fetch schema
    const schema = await fetchSchema();
    console.log(`✅ Found ${schema.tables.length} table(s)\n`);

    // Generate types file
    console.log('📝 Generating types file...');
    const typesContent = generateTypesFile(schema);
    writeFile(GENERATED_TYPES_PATH, typesContent);
    console.log(`   ✓ Created: ${GENERATED_TYPES_PATH}\n`);

    // Generate service and hook files for each table
    console.log('📝 Generating service and hook files...');
    schema.tables.forEach(table => {
      const serviceName = toCamelCase(table.name);
      const servicePath = path.join(GENERATED_SERVICES_DIR, `${serviceName}.service.ts`);
      const serviceContent = generateServiceFile(table);
      writeFile(servicePath, serviceContent);
      console.log(`   ✓ Created service: ${servicePath}`);

      const hookName = `use${toPascalCase(table.name)}`;
      const hookPath = path.join(GENERATED_HOOKS_DIR, `${hookName}.ts`);
      const hookContent = generateHookFile(table);
      writeFile(hookPath, hookContent);
      console.log(`   ✓ Created hook: ${hookPath}`);
    });

    console.log('\n✨ Schema generation completed successfully!');
    console.log('\n📋 Generated files:');
    console.log(`   - ${schema.tables.length} type interface(s)`);
    console.log(`   - ${schema.tables.length} service file(s)`);
    console.log(`   - ${schema.tables.length} hook file(s)`);
    console.log('\n💡 You can now use the generated hooks and services in your React components!');
    
  } catch (error) {
    console.error('\n❌ Schema generation failed:');
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
};

// Run the script
main();
